### ISSUE TITLE
Type limitation on values arbitrary?

### ISSUE THREAD

**Issue by pudelkoM** [preshing/junction#27]
I'm trying to use the leapfrog hashmap in the context of packet processing and flow tracking.
Ideally the flow data would be stored directly in the hash table to mitigate the whole issue of memory allocations. But according to your blog posts and the readme, value types are limited to integers and pointers.
I understand the restrictions on key types because of the hash reversibility requirement, but do not see why value types are limited as well. As long as I provide a ValueTraits::NullValue and ValueTraits::Redirect any value could work, right?

For reference, a value would essentially be a [POD](http://en.cppreference.com/w/cpp/concept/PODType) struct:
```
struct flow_data {
    uint64_t timestamp;
    bool someflag;
    uint16_t another_value;
};
```

**Comment by preshing** [comment]
Value types are limited because it has to be possible to read or write them atomically. Your `flow_data` struct is larger than 8 bytes so you either need to store a pointer to `flow_data` in the table, or the hash table needs to be extended to use a 16-byte CAS (which is only present on 64-bit platforms).

**Comment by pudelkoM** [comment]
That makes sense but is nonetheless unfortunate. I'll try to find a solution.

Thanks for your quick response.
