### ISSUE TITLE
Please document what source files are needed for those who want to do that way

### ISSUE THREAD

**Issue by abletaz** [preshing/junction#43]
You acknowledge in the docs that some devs prefer just including the required headers + cpp files in their project. However it would be extremely useful if you, for those devs, could clearly explain precisely what headers + cpp files are required in order to do this (plus any compile flags or anything additional to be wary of).

Note - there are many many reasons / use-cases why (manually adding the required files to whatever ones build setup is) can be strongly preferred and often even as in my case really the only viable option. It's worth being aware that, whatever your opinions on the topic, many devs like me will simply write-off as 'not worth taking the time to work-out how to integrate it in order to try it' any library that doesn't make such a mode of inclusion clear+simple (thus especially favouring [single] header-only libraries. though that's likely not a sensible option here) ... and thus adding such an explanation would surely broaden the amount that your by all appearances rather useful work will be used.

**Comment by preshing** [comment]
Hi abletaz. Unfortunately I just don't have time to fulfill such requests. This project is experimental with a narrow use case and I'm not looking to make it any more popular than it is. If you could really use help integrating it, I might consider consulting for a fee; otherwise you can look into alternatives such as https://github.com/efficient/libcuckoo
