### ISSUE TITLE
can't compile with g++ 4.4.7

### ISSUE THREAD

**Issue by spetrel** [preshing/junction#8]
in turf/cmake/Macros.cmake, you set(CMAKE_CXX_FLAGS "-g -std=c++11...)
this doesn't make sense. because this lib suppose to work without c++11

**Comment by preshing** [comment]
You're right, I should probably tie it to the TURF_PREFER_CPP11 configuration. I tried to avoid C++11 in the lib but I still it for atomics on PowerPC and AArch64 at the moment.

Did you try building without the flag?

**Comment by spetrel** [comment]
Yes, I pass the building after drop the flag.

2016-05-09 8:12 GMT+08:00 Jeff Preshing <notifications@github.com>:

**Comment by preshing** [comment]
As of 39e02b3 (and preshing/turf@910844c) you can pass -DTURF_ENABLE_CPP11=FALSE to the CMake command line and it won't use -std=c++11 anymore. I also made a lot of fixes so that it actually builds with C++98 (tested with GCC 5.2.1).

I decided to leave it enabled in the CMake scripts by default simply because I use Turf in some other projects that do take advantage of C++11.
