### ISSUE TITLE
Make turf a git submodule

### ISSUE THREAD

**Issue by weshoke** [preshing/junction#9]
Why not make turf a git submodule?  Seems like it would be best to pin a specific version of turf to a specific version of junction to avoid breaking the compilation and tracking the API interface between projects with version control.

**Comment by preshing** [comment]
Hi weshoke. To be honest I just find it a bit more straightforward without submodules. (I found them a bit cumbersome in the past, but maybe git has improved since then). And changes to junction/turf are pretty infrequent so I don't think API breaks are a big problem. (The main reason turf is a separate repo is because I use it in other projects.)
